name: Node.js CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
    - uses: popsiclestick/gist-sync-action@v1.2.0
            id: sync
            with:
              auth: ${{ secrets.GIST_TOKEN }}
              gist_url: https://gist.github.com/saabi/ca24af64f2473c67b5da4e772987c569
              gist_title: Example Gist Title
              gist_description: Example Gist Description
              github_file: report.json